### ISSUE TITLE
What versions of Linux does this work on?

### ISSUE THREAD

**Issue by LegitDax009** [Fullmetal5/bluebomb#2]
just wondering

**Comment by Leseratte10** [comment]
I don't think it really matters. I used Ubuntu, but as long as it supports your bluetooth module you should be able to use any distribution. Though if you have never used Linux before and just want to use a live disc I'd suggest Ubuntu just because it's the most popular one and it's easier to get support.

**Comment by 2secslater** [comment]
As long as the distribution you are using works with BlueZ and your Bluetooth card/dongle works, it should work.

**Comment by LegitDax009** [comment]
Okay thanks
